backend:
  name: github
  repo: chovex777-tech/Panita-Panaderia
  branch: main
  base_url: https://chovex777-tech.github.io/Panita-Panaderia

media_folder: "assets/img/products"
public_folder: "/assets/img/products"

collections:
  - name: "productos"
    label: "🍞 Productos"
    folder: "data/productos"
    create: true
    extension: json
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Precio", name: "precio", widget: "number" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imagen", name: "imagen", widget: "image", required: false }
